### ISSUE TITLE
non dll-interface class 'boost::noncopyable_::noncopyable' used as base for dll-interface class 'boost::contract::detail::checking'

### ISSUE THREAD

**Issue by jeking3** [boostorg/contract#23]
This is from a teeks msvc 14.2 build that boost-ci doesn't have in it yet.  Likely all other windows builds are issuing the same warning however.

https://www.boost.org/development/tests/master/developer/output/teeks99-07-v16ml-64onAMD64-boost-bin-v2-libs-contract-test-specify-auto_error-test-msvc-14-2-dbg-adrs-mdl-64-thrd-mlt.html

```
D:\teeks99-07\run\boost_root\boost/contract/detail/checking.hpp(26): warning C4275: non dll-interface class 'boost::noncopyable_::noncopyable' used as base for dll-interface class 'boost::contract::detail::checking'
D:\teeks99-07\run\boost_root\boost/core/noncopyable.hpp(38): note: see declaration of 'boost::noncopyable_::noncopyable'
D:\teeks99-07\run\boost_root\boost/contract/detail/checking.hpp(24): note: see declaration of 'boost::contract::detail::checking'
```

**Comment by lcaminiti** [comment]
I fixed quire a few warnings in develop (but I haven't merged into master yet). Looking at the test matrix for develop I don't see warning for msvc-14.2:
https://www.boost.org/development/tests/develop/developer/contract.html
The link above is from master. Is the warning C4275 above from develop or master?

**Comment by jeking3** [comment]
Looks like it was from master.

**Comment by lcaminiti** [comment]
This should be fixed in develop.
